/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ExperienceRouteImport } from './routes/experience'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExperienceIndexRouteImport } from './routes/experience.index'
import { Route as ExperienceStandardBankRouteImport } from './routes/experience.standard-bank'
import { Route as ExperiencePreviousRouteImport } from './routes/experience.previous'
import { Route as ExperienceMahindraFinanceRouteImport } from './routes/experience.mahindra-finance'
import { Route as ExperienceIbmRouteImport } from './routes/experience.ibm'
import { Route as ExperienceHdfcRouteImport } from './routes/experience.hdfc'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceRoute = ExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceIndexRoute = ExperienceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExperienceRoute,
} as any)
const ExperienceStandardBankRoute = ExperienceStandardBankRouteImport.update({
  id: '/standard-bank',
  path: '/standard-bank',
  getParentRoute: () => ExperienceRoute,
} as any)
const ExperiencePreviousRoute = ExperiencePreviousRouteImport.update({
  id: '/previous',
  path: '/previous',
  getParentRoute: () => ExperienceRoute,
} as any)
const ExperienceMahindraFinanceRoute =
  ExperienceMahindraFinanceRouteImport.update({
    id: '/mahindra-finance',
    path: '/mahindra-finance',
    getParentRoute: () => ExperienceRoute,
  } as any)
const ExperienceIbmRoute = ExperienceIbmRouteImport.update({
  id: '/ibm',
  path: '/ibm',
  getParentRoute: () => ExperienceRoute,
} as any)
const ExperienceHdfcRoute = ExperienceHdfcRouteImport.update({
  id: '/hdfc',
  path: '/hdfc',
  getParentRoute: () => ExperienceRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/experience': typeof ExperienceRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/experience/hdfc': typeof ExperienceHdfcRoute
  '/experience/ibm': typeof ExperienceIbmRoute
  '/experience/mahindra-finance': typeof ExperienceMahindraFinanceRoute
  '/experience/previous': typeof ExperiencePreviousRoute
  '/experience/standard-bank': typeof ExperienceStandardBankRoute
  '/experience/': typeof ExperienceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/experience/hdfc': typeof ExperienceHdfcRoute
  '/experience/ibm': typeof ExperienceIbmRoute
  '/experience/mahindra-finance': typeof ExperienceMahindraFinanceRoute
  '/experience/previous': typeof ExperiencePreviousRoute
  '/experience/standard-bank': typeof ExperienceStandardBankRoute
  '/experience': typeof ExperienceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/experience': typeof ExperienceRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/experience/hdfc': typeof ExperienceHdfcRoute
  '/experience/ibm': typeof ExperienceIbmRoute
  '/experience/mahindra-finance': typeof ExperienceMahindraFinanceRoute
  '/experience/previous': typeof ExperiencePreviousRoute
  '/experience/standard-bank': typeof ExperienceStandardBankRoute
  '/experience/': typeof ExperienceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/experience'
    | '/sitemap.xml'
    | '/experience/hdfc'
    | '/experience/ibm'
    | '/experience/mahindra-finance'
    | '/experience/previous'
    | '/experience/standard-bank'
    | '/experience/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/sitemap.xml'
    | '/experience/hdfc'
    | '/experience/ibm'
    | '/experience/mahindra-finance'
    | '/experience/previous'
    | '/experience/standard-bank'
    | '/experience'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/experience'
    | '/sitemap.xml'
    | '/experience/hdfc'
    | '/experience/ibm'
    | '/experience/mahindra-finance'
    | '/experience/previous'
    | '/experience/standard-bank'
    | '/experience/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ExperienceRoute: typeof ExperienceRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience': {
      id: '/experience'
      path: '/experience'
      fullPath: '/experience'
      preLoaderRoute: typeof ExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience/': {
      id: '/experience/'
      path: '/'
      fullPath: '/experience/'
      preLoaderRoute: typeof ExperienceIndexRouteImport
      parentRoute: typeof ExperienceRoute
    }
    '/experience/standard-bank': {
      id: '/experience/standard-bank'
      path: '/standard-bank'
      fullPath: '/experience/standard-bank'
      preLoaderRoute: typeof ExperienceStandardBankRouteImport
      parentRoute: typeof ExperienceRoute
    }
    '/experience/previous': {
      id: '/experience/previous'
      path: '/previous'
      fullPath: '/experience/previous'
      preLoaderRoute: typeof ExperiencePreviousRouteImport
      parentRoute: typeof ExperienceRoute
    }
    '/experience/mahindra-finance': {
      id: '/experience/mahindra-finance'
      path: '/mahindra-finance'
      fullPath: '/experience/mahindra-finance'
      preLoaderRoute: typeof ExperienceMahindraFinanceRouteImport
      parentRoute: typeof ExperienceRoute
    }
    '/experience/ibm': {
      id: '/experience/ibm'
      path: '/ibm'
      fullPath: '/experience/ibm'
      preLoaderRoute: typeof ExperienceIbmRouteImport
      parentRoute: typeof ExperienceRoute
    }
    '/experience/hdfc': {
      id: '/experience/hdfc'
      path: '/hdfc'
      fullPath: '/experience/hdfc'
      preLoaderRoute: typeof ExperienceHdfcRouteImport
      parentRoute: typeof ExperienceRoute
    }
  }
}

interface ExperienceRouteChildren {
  ExperienceHdfcRoute: typeof ExperienceHdfcRoute
  ExperienceIbmRoute: typeof ExperienceIbmRoute
  ExperienceMahindraFinanceRoute: typeof ExperienceMahindraFinanceRoute
  ExperiencePreviousRoute: typeof ExperiencePreviousRoute
  ExperienceStandardBankRoute: typeof ExperienceStandardBankRoute
  ExperienceIndexRoute: typeof ExperienceIndexRoute
}

const ExperienceRouteChildren: ExperienceRouteChildren = {
  ExperienceHdfcRoute: ExperienceHdfcRoute,
  ExperienceIbmRoute: ExperienceIbmRoute,
  ExperienceMahindraFinanceRoute: ExperienceMahindraFinanceRoute,
  ExperiencePreviousRoute: ExperiencePreviousRoute,
  ExperienceStandardBankRoute: ExperienceStandardBankRoute,
  ExperienceIndexRoute: ExperienceIndexRoute,
}

const ExperienceRouteWithChildren = ExperienceRoute._addFileChildren(
  ExperienceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ExperienceRoute: ExperienceRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
